/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_BATTERY_STATUS_PB_H_INCLUDED
#define PB_BATTERY_STATUS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _BatteryStatus {
    /* Battery voltage (e.g., 3.7 or 4.2) */
    float voltage;
    /* Estimated battery percentage (0-100) */
    int32_t percentage;
    /* True if plugged in/charging */
    bool is_charging;
} BatteryStatus;

typedef struct _HeartMeasurementData {
    /* Raw PPG heart rate signal reading */
    int32_t ppg_value;
} HeartMeasurementData;

typedef struct _DeviceData {
    /* Heart measurement sub-message */
    HeartMeasurementData heart_measurement;
    /* Battery status sub-message */
    BatteryStatus battery_status;
} DeviceData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define BatteryStatus_init_default               {0, 0, 0}
#define HeartMeasurementData_init_default        {0}
#define DeviceData_init_default                  {HeartMeasurementData_init_default, BatteryStatus_init_default}
#define BatteryStatus_init_zero                  {0, 0, 0}
#define HeartMeasurementData_init_zero           {0}
#define DeviceData_init_zero                     {HeartMeasurementData_init_zero, BatteryStatus_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define BatteryStatus_voltage_tag                1
#define BatteryStatus_percentage_tag             2
#define BatteryStatus_is_charging_tag            3
#define HeartMeasurementData_ppg_value_tag       1
#define DeviceData_heart_measurement_tag         1
#define DeviceData_battery_status_tag            2

/* Struct field encoding specification for nanopb */
#define BatteryStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    voltage,           1) \
X(a, STATIC,   SINGULAR, INT32,    percentage,        2) \
X(a, STATIC,   SINGULAR, BOOL,     is_charging,       3)
#define BatteryStatus_CALLBACK NULL
#define BatteryStatus_DEFAULT NULL

#define HeartMeasurementData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    ppg_value,         1)
#define HeartMeasurementData_CALLBACK NULL
#define HeartMeasurementData_DEFAULT NULL

#define DeviceData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  heart_measurement,   1) \
X(a, STATIC,   SINGULAR, MESSAGE,  battery_status,    2)
#define DeviceData_CALLBACK NULL
#define DeviceData_DEFAULT NULL
#define DeviceData_heart_measurement_MSGTYPE HeartMeasurementData
#define DeviceData_battery_status_MSGTYPE BatteryStatus

extern const pb_msgdesc_t BatteryStatus_msg;
extern const pb_msgdesc_t HeartMeasurementData_msg;
extern const pb_msgdesc_t DeviceData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define BatteryStatus_fields &BatteryStatus_msg
#define HeartMeasurementData_fields &HeartMeasurementData_msg
#define DeviceData_fields &DeviceData_msg

/* Maximum encoded size of messages (where known) */
#define BATTERY_STATUS_PB_H_MAX_SIZE             DeviceData_size
#define BatteryStatus_size                       18
#define DeviceData_size                          33
#define HeartMeasurementData_size                11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
