/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "battery_status.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(BatteryStatus, BatteryStatus, AUTO)


PB_BIND(HeartMeasurementData, HeartMeasurementData, AUTO)


PB_BIND(DeviceData, DeviceData, AUTO)



